### PR TITLE
Release to Maven Central, add OSGi metadata

### PR DESCRIPTION
**Pull request by ibauersachs**

### CODE REVIEW

**Review by bbaldino — COMMENTED** [review]
Did you get rid of the code coverage action?

**Comment by ibauersachs** [comment]
It's integrated into the Java 8 build as the last step. Did I miss something?

**Comment by bbaldino** [comment]
I dunno, I saw we used to run `jacoco:report` on maven and now don't see that (just a call to `verify`--will that implicitly run `jacoco:report`?)

**Comment by ibauersachs** [comment]
Yes, because the JaCoCo `report` goal is bound to the `test` phase in the pom. The report from codecov is posted as a comment, that wouldn't be here if it were missing. `verify` runs everything up to but excluding the `install` phase (if you're interested: https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html).

**Comment by bbaldino** [comment]
Ok, I didn't remember that it was bound to test but I just ran that locally and see it does do a quick jacoco line.  I don't know that's actually what we'd want, but, it seems to be quick enough that it isn't noticeable.

**Comment by ibauersachs** [comment]
That was already there, so I took advantage of it. I can also unbind it and run `mvn -B verify jacoco:report`, that's the same result for the PR.

**Review by bbaldino — APPROVED** [review]
Really wish we could include poms or something so the main one didn't have to get all muddied up with stuff like this (i.e. have deploy stuff in one include, core deps, etc. in another).

**Comment by ibauersachs** [comment]
We used to have that - [jitsi-universe](https://github.com/jitsi/jitsi-universe). It was a mess.

I could be convinced to reintroduce a parent pom for the plugins required to release to Maven Central, but definitely not for any sort of build dependencies.

**Comment by bbaldino** [comment]
Yeah, the parent could be workable for the deployment, but I was just wishing poms supported some kind of include system in general (not just the parent mechanism) so we could split out the different pieces into different poms which could just be included by `pom.xml`.

**Comment by ibauersachs** [comment]
There's this thing called [BOM](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms) which I never used, maybe worth taking a deeper look. But in the end it would still be:
- update library
- update BOM/parent/whatever
- update consuming project to new BOM/parent

XML entities could also possible be used, but I don't think that would be a good idea a) because it doesn't really make it simpler to read and b) because it would probably stumble parsers like GitHubs automated security scanner. Not sure there's really anything that could neatly solve it without a monorepo and perhaps another build system like Gradle or Bazel (which both have inferior support in IntelliJ).

The one thing that really could thelp though would be a custom GitHub action (or yaml includes, whatever) so that if we'd decide to release binaries as Java 11 we wouldn't have to change dozens of yamls. I didn't invest too much time into that yet because I'm pretty sure GitHub will improve in that area in the not to soon future.

**Pull request merged**
